PRAGMA journal_mode=OFF;
PRAGMA synchronous=OFF;
PRAGMA temp_store=MEMORY;
PRAGMA cache_size=262144;  
CREATE TABLE n(i INTEGER PRIMARY KEY);
WITH RECURSIVE t(x) AS (VALUES(0) UNION ALL SELECT x+1 FROM t WHERE x<999) INSERT INTO n SELECT x FROM t;
CREATE TABLE kv(k INTEGER PRIMARY KEY, v BLOB);
INSERT INTO kv SELECT a.i + 1000*b.i + 1, randomblob(256) FROM n a, n b;  
SELECT sum(length(v)) FROM kv;   
WITH RECURSIVE r(i) AS (VALUES(0) UNION ALL SELECT i+1 FROM r WHERE i<499999) SELECT sum(length((SELECT v FROM kv WHERE
k=(abs(random())%1000000)+1))) FROM r;